#!/bin/bash

if [ -n "$DEBUG" ]; then
    PS4=':${LINENO}+'
    set -x
fi

TARGET_NAME="$(basename "$0")"
TIMESTAMP=$(date --iso-8601=seconds)
TARBALL="$TIMESTAMP.tar.gz"
RMRF_CFG=~/.config/rmrf/rmrf.cfg
BKUP_CFG=~/.config/bkup/bkup.cfg
SUDO=""

[ -f "$RMRF_CFG" ] && source <(grep = $RMRF_CFG | sed 's/ *= */=/g')
[ -f "$BKUP_CFG" ] && source <(grep = $BKUP_CFG | sed 's/ *= */=/g')

RMRF_PATH="${RMRF_PATH:-/var/tmp/rmrf}"
RMRF_SUDO="${RMRF_SUDO:-yes}"
RMRF_KEEP="${RMRF_KEEP:-21}"

BKUP_PATH="${BKUP_PATH:-/var/tmp/bkup}"
BKUP_SUDO="${BKUP_SUDO:-yes}"

FILES=()
for FILE in "${@}"; do
    FILES+=("$(realpath "$FILE")")
done
usage() {
    echo "usage"
    exit -1
}

do_bkup() {
    DIR_PATH="$1"
    [ "$BKUP_SUDO" == "yes" ] && SUDO=sudo
    if [[ "${FILES[0]}" == "$DIR_PATH/"* ]]; then
        echo "${FILES[0]} ->"
        "$SUDO" tar --absolute-names -xvf "${FILES[0]}" | sed 's/^/  /'
        exit 0
    fi
    mkdir -p "$DIR_PATH"
    "$SUDO" tar --force-local --absolute-names --preserve-permissions --create --verbose --gzip --file "$TARBALL" "${FILES[@]}"
    "$SUDO" mv "$TARBALL" "$DIR_PATH"
    echo "-> $DIR_PATH/$TARBALL"
    exit 0
}

do_rmrf() {
    DIR_PATH="$1"
    [ "$RMRF_SUDO" == "yes" ] && SUDO=sudo
    do_bkup "$DIR_PATH"
    DELETED=$(find "$DIR_PATH" -mtime "+$RMRF_KEEP")
    if [ -n "$DELETED" ]; then
        echo "$DELETED"
        echo "-> /dev/null"
    fi
    "$SUDO" find "$DIR_PATH" -mtime "+$RMRF_KEEP" -delete
    "$SUDO" rm -rf "${FILES[@]}"
    exit 0
}

do_list() {
    DIR_PATH="$1"
    for TARBALL in "$DIR_PATH/"*; do
        echo "$TARBALL"
        sudo tar --absolute-names -tvf "$TARBALL" | grep -v ^d | sed 's/^/  /'
    done
    exit 0
}

case "$TARGET_NAME" in
    bkup)
        do_bkup "$BKUP_PATH"
        ;;
    rmrf)
        do_rmrf "$RMRF_PATH"
        ;;
    ls-bkup)
        do_list "$BKUP_PATH"
        ;;
    ls-rmrf)
        do_list "$RMRF_PATH"
        ;;
    *)
        usage
        ;;
esac
